language: python
python:
  - "3.6"
install:
  - python3 -m pip install -r requirements.txt
script:
  - python3 manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: false
  region: "us-east-2"  
  app: "PayHub"
  env: $ELASTIC_BEANSTALK_ENV
  bucket_name: $S3_BUCKET_NAME

notifications:
  email:
    - armaangupta01@gmail.com
  on_failure: always